
[functions.forgot-password]
enabled = true
verify_jwt = true
import_map = "./functions/forgot-password/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/forgot-password/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/forgot-password/*.html" ]

[functions.seed-demo-auth]
enabled = true
verify_jwt = true
import_map = "./functions/seed-demo-auth/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/seed-demo-auth/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/seed-demo-auth/*.html" ]
